apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-developer-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jegan2476/gitops-demo.git   # <-- Replace with your GitHub URL
    targetRevision: main
    path: ./ 
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
